#Resource locations of disallowed actions. Trying to cast one of these will result in a mishap.
actionDenyList = ["hexcasting:alter_scale"]
#Should villagers take offense when you flay the mind of their fellow villagers?
villagersOffendedByMindMurder = true
#Resource locations of dimensions you can't Blink or Greater Teleport in.
tpDimDenyList = ["twilightforest:twilight_forest"]

[Spells]
	#How many times a spell can recursively cast other spells
	#Range: > 0
	maxRecurseDepth = 512
	#The harvest level of the Break Block spell.
	#0 = wood, 1 = stone, 2 = iron, 3 = diamond, 4 = netherite.
	#Range: 0 ~ 4
	opBreakHarvestLevel = 3

["Spell Circles"]
	#The maximum number of slates in a spell circle
	#Range: > 4
	maxSpellCircleLength = 1024
	#Resource locations of disallowed actions within circles. Trying to cast one of these in a circle will result in a mishap.
	circleActionDenyList = []

["Scrolls in Loot"]
	#Which loot tables should a small number of Ancient Scrolls be injected into?
	fewScrollTables = ["minecraft:chests/jungle_temple", "minecraft:chests/simple_dungeon", "minecraft:chests/village/village_cartographer"]
	#Which loot tables should a decent number of Ancient Scrolls be injected into?
	someScrollTables = ["minecraft:chests/bastion_treasure", "minecraft:chests/shipwreck_map"]
	#Which loot tables should a huge number of Ancient Scrolls be injected into?
	manyScrollTables = ["minecraft:chests/stronghold_library"]